### ISSUE TITLE
when selecting stored procedure instead "show databases" , "end" is called twice problem.

### ISSUE THREAD

**Issue by Chiy** [mscdex/node-mariasql#26]
[ procedure] 
DELIMITER //
DROP PROCEDURE  IF EXISTS SP_SEL_DEPARTMENTS_01;
USE employees;
CREATE PROCEDURE SP_SEL_DEPARTMENTS_01()
BEGIN	
		SELECT DEPT_NO, DEPT_NAME FROM DEPARTMENTS;
END//

DELIMITER ;

[node.js file] 

     c.query('call SP_SELECT_DEPT_MANAGER()')
        .on('result', function(res) {
            res.on('row', function(row) {
                self.data[self.data.length] = row ;
            })
            .on('error', function(err) {
                console.log('Result error: ' + inspect(err));
                })
            .on('end', function(info) {
                console.log('Result finished successfully');
                });
        })
        .on('end', function() {
            console.log('Done with all results');
            callback(null, self.data);
        });

[result ]
Result finished successfully
Result finished successfully
Done with all results

=> Why res.on('end', ...) is called twice? Other insert procedure or query is called once.

**Comment by mscdex** [comment]
This is fixed in the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite).

**Comment by dOESoNE** [comment]
This is still have problem.
mariasql@0.2.5

Stored Procedure:
```
CREATE DEFINER=`node`@`%` PROCEDURE `getTimestamp`()
BEGIN
	SELECT current_timestamp();
END
```

Javascript:
```
dbConnection.query('CALL getTimestamp();', null, { useArray: true }).on('result', function (res) {
	res.on('data', function (row) {
		console.log('result-data: ' + row);
	}).on('end', function () {
		console.log('result-end: ' + (new Date()).toUTCString());
	});
}).on('end', function () {
	console.log('END: list');
	dbConnection.end();
});
```

Results:

```
result-data: 2016-03-09 10:32:50
result-end: Wed, 09 Mar 2016 01:32:49 GMT
result-end: Wed, 09 Mar 2016 01:32:49 GMT
END: list
```

How can I fix it?
